# Generated by Django 5.0.7 on 2024-07-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=models.CharField(max_length=200),
        ),
    ]
